---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toodlepip-website
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: toodlepip-website-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HMAC_SECRET: "{{ .HMAC_SECRET }}"
  dataFrom:
    - extract:
        key: toodlepip-website
