---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: n8n-secret
    template:
      engineVersion: v2
      data:
        # n8n configuration
        N8N_DB_PASSWORD: &dbPass "{{ .N8N_DB_PASSWORD }}"
        DB_POSTGRESDB_PASSWORD: *dbPass
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        N8N_USER_MANAGEMENT_JWT_SECRET: "{{ .N8N_USER_MANAGEMENT_JWT_SECRET }}"

        # Database configuration
        INIT_POSTGRES_DBNAME: &dbName n8n
        INIT_POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbUser n8n
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
