global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp-relay.default.svc.cluster.local:25'
  smtp_from: 'tgreen@albatrossflavour.com'
route:
  group_by: ["alertname", "job"]
  group_interval: 10m
  group_wait: 1m
  receiver: pushover
  repeat_interval: 12h
  routes:
    - receiver: heartbeat
      group_interval: 5m
      group_wait: 0s
      matchers:
        - alertname =~ "Watchdog"
      repeat_interval: 5m
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor"
    - receiver: pushover
      continue: true
      matchers:
        - severity = "critical"
inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
receivers:
  - name: heartbeat
    webhook_configs:
      - send_resolved: true
        url: "https://alertmanager.albatrossflavour.com"
  - name: "null"
  - name: 'sys-admin-email'
    email_configs:
      - to: 'tgreen@albatrossflavour.com'
        require_tls: false
  - name: pushover
    pushover_configs:
      - html: true
        message: |-
          {{- range .Alerts }}
            {{- if ne .Annotations.description "" }}
              {{ .Annotations.description }}
            {{- else if ne .Annotations.summary "" }}
              {{ .Annotations.summary }}
            {{- else if ne .Annotations.message "" }}
              {{ .Annotations.message }}
            {{- else }}
              Alert description not available
            {{- end }}
            {{- if gt (len .Labels.SortedPairs) 0 }}
              <small>
              {{- range .Labels.SortedPairs }}
                <b>{{ .Name }}:</b> {{ .Value }}
              {{- end }}
              </small>
            {{- end }}
          {{- end }}
        priority: |-
          {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
        send_resolved: true
        sound: gamelan
        # ttl: 1d
        title: >-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
          {{ .CommonLabels.alertname }}
        token: "au7gg8h2f9bhuf2afim9a9ppmn2etk"
        url_title: View in Alertmanager
        user_key: "gmr5dfv1im5516aa7s2cmmhxb2yw63"
