---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./qbittorrent/ks.yaml
  #- ./overseerr/ks.yaml
  - ./tautulli/ks.yaml
  - ./prowlarr/ks.yaml
  - ./flaresolverr/ks.yaml
