---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./it-tools/ks.yaml
  - ./jsoncrack/ks.yaml
  - ./cyberchef/ks.yaml
  - ./n8n/ks.yaml
  - ./node-red/ks.yaml
  - ./send/ks.yaml
  - ./pdi-keepalive/ks.yaml
  - ./gotenberg/ks.yaml
  - ./shlink/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./drawio/ks.yaml
