---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./it-tools/ks.yaml
  - ./jsoncrack/ks.yaml
  - ./cyberchef/ks.yaml
  - ./n8n/ks.yaml
  - ./send/ks.yaml
