[filters]
# Add custom filters to reduce false positives
exclude_lines = [
    # External Secrets references - these are not actual secrets
    "secretKey:.*",
    "remoteRef:.*",
    "property:.*",
    # Kubernetes secret references
    "secretKeyRef:.*",
    "valueFrom:.*",
    # Common false positive patterns in k8s manifests
    "existingSecret:.*",
    "secretName:.*",
]

exclude_files = [
    # SOPS encrypted files are already encrypted
    ".*\\.sops\\.ya?ml$",
    # External Secret manifests don't contain actual secrets
    ".*/externalsecret\\.ya?ml$",
    # Bootstrap and generated files
    "bootstrap/.*",
    ".*/(templates|crds)/.*",
]
