---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  PRIVATE_DIR: "{{.ROOT_DIR}}/.private"
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  # Files
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  BOOTSTRAP_CONFIG_FILE: "{{.ROOT_DIR}}/config.yaml"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/kubeconfig"
  MAKEJINJA_CONFIG_FILE: "{{.ROOT_DIR}}/makejinja.toml"
  PIP_REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
  SOPS_CONFIG_FILE: "{{.ROOT_DIR}}/.sops.yaml"
  # Binaries
  PYTHON_BIN: python3

env:
  KUBECONFIG: "{{.KUBECONFIG_FILE}}"
  PYTHONDONTWRITEBYTECODE: "1"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"

includes:
  kubernetes: .taskfiles/Kubernetes
  flux: .taskfiles/Flux
  repository: .taskfiles/Repository
  talos: .taskfiles/Talos
  sops: .taskfiles/Sops
  workstation: .taskfiles/Workstation
  user:
    taskfile: .taskfiles/User
    optional: true

tasks:

  default: task --list

  init:
    desc: Initialize configuration files
    cmds:
      - cp -n {{.BOOTSTRAP_CONFIG_FILE | replace ".yaml" ".sample.yaml"}} {{.BOOTSTRAP_CONFIG_FILE}}
      - cmd: echo === Configuration file copied ===
      - cmd: echo Proceed with updating the configuration files...
      - cmd: echo {{.BOOTSTRAP_CONFIG_FILE}}
    status:
      - test -f {{.BOOTSTRAP_CONFIG_FILE}}

  commit-and-push:
    desc: Auto-commit and push with pre-commit retry
    cmds:
      - task: commit
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"
      - git push
    silent: true

  configure:
    desc: Configure repository from bootstrap vars
    prompt: Any conflicting config in the kubernetes directory will be overwritten... continue?
    deps: ["workstation:direnv", "workstation:venv", "sops:age-keygen", "init"]
    cmds:
      - task: .template
      - task: sops:encrypt
      - task: .validate

  backup:create:
    desc: Backup critical infrastructure files to 1Password
    summary: |
      Backs up critical files that are not stored in the Git repository to 1Password:
      - age.key (SOPS encryption key)
      - config.yaml (bootstrap configuration)
      - kubeconfig and talosconfig (cluster access)
      - bootstrap/ directory (templates)
    cmds:
      - "{{.SCRIPTS_DIR}}/backup-to-1password.sh"
    preconditions:
      - msg: 1Password CLI not found - install from https://developer.1password.com/docs/cli/get-started/
        sh: command -v op
      - msg: Not authenticated with 1Password CLI - run 'op signin'
        sh: op vault list >/dev/null 2>&1
      - msg: Missing backup script
        sh: test -f {{.SCRIPTS_DIR}}/backup-to-1password.sh

  backup:restore:
    desc: Restore critical infrastructure files from 1Password
    summary: |
      Restores critical files from 1Password to a timestamped directory.
      Files are restored to restored-YYYYMMDD-HHMMSS/ for safe review.
      This command will NOT overwrite existing files.
    cmds:
      - "{{.SCRIPTS_DIR}}/restore-from-1password.sh"
    preconditions:
      - msg: 1Password CLI not found - install from https://developer.1password.com/docs/cli/get-started/
        sh: command -v op
      - msg: Not authenticated with 1Password CLI - run 'op signin'
        sh: op vault list >/dev/null 2>&1
      - msg: Missing restore script
        sh: test -f {{.SCRIPTS_DIR}}/restore-from-1password.sh

  backup:list:
    desc: List backed up items in 1Password vault
    summary: |
      Shows all homeops backup items currently stored in the 1Password vault.
      Useful for verifying backups exist before attempting restore.
    cmds:
      - op item list --vault="discworld" | grep "homeops-" || echo "No backup items found"
    preconditions:
      - msg: 1Password CLI not found - install from https://developer.1password.com/docs/cli/get-started/
        sh: command -v op
      - msg: Not authenticated with 1Password CLI - run 'op signin'
        sh: op vault list >/dev/null 2>&1

  .template:
    internal: true
    cmd: "{{.VIRTUAL_ENV}}/bin/makejinja"
    preconditions:
      - msg: Missing virtual environment
        sh: test -d {{.VIRTUAL_ENV}}
      - msg: Missing Makejinja config file
        sh: test -f {{.MAKEJINJA_CONFIG_FILE}}
      - msg: Missing Makejinja plugin file
        sh: test -f {{.BOOTSTRAP_DIR}}/scripts/plugin.py
      - msg: Missing bootstrap config file
        sh: test -f {{.BOOTSTRAP_CONFIG_FILE}}

  .validate:
    internal: true
    cmds:
      - task: kubernetes:kubeconform
      - cmd: echo === Done rendering and validating YAML ===
      - cmd: |
          if [[ $KUBECONFIG != "{{.KUBECONFIG_FILE}}" ]]; then
            echo WARNING: KUBECONFIG is not set to the expected value, this may cause conflicts.
          fi
      - cmd: |
          if [[ $SOPS_AGE_KEY_FILE != "{{.AGE_FILE}}" ]]; then
            echo WARNING: SOPS_AGE_KEY_FILE is not set to the expected value, this may cause conflicts.
          fi
      - cmd: |
          if test -f ~/.config/sops/age/keys.txt; then
            echo WARNING: SOPS Age key found in home directory, this may cause conflicts.
          fi
    silent: true
