# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app shlink-web
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      shlink-web:
        containers:
          app:
            image:
              repository: shlinkio/shlink-web-client
              tag: "4.2.0@sha256:c3b693b0e647b5fbb6509c9bafc2bedc52ed6ab7608d31699e74333a7ecc69e3"
            env:
              TZ: Australia/Sydney
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 64Mi
              limits:
                memory: 256Mi
    service:
      app:
        controller: shlink-web
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Utilities"
          gethomepage.dev/name: "Shlink Web"
          gethomepage.dev/icon: "shlink.png"
          gethomepage.dev/description: "URL Shortener Web UI"
        hosts:
          - host: shlink.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
