---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kapowarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kapowarr-secret
    template:
      engineVersion: v2
      data:
        KAPOWARR__AUTH__APIKEY: "{{ .KAPOWARR_API_KEY }}"
        KAPOWARR__POSTGRES__HOST: &dbHost postgres16-rw.database.svc.cluster.local
        KAPOWARR__POSTGRES__PORT: &dbPort "5432"
        KAPOWARR__POSTGRES__USER: &dbUser "{{ .KAPOWARR_POSTGRES_USER }}"
        KAPOWARR__POSTGRES__PASSWORD: &dbPass "{{ .KAPOWARR_POSTGRES_PASSWORD }}"
        KAPOWARR__POSTGRES__MAINDB: &dbName kapowarr_main
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_PORT: *dbPort
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: kapowarr
