---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "www.toodlepip.com.au"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "toodlepip.com.au"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "www.bandcamp.tv"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "bandcamp.tv"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "puppet.lab.albatrossflavour.com"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "cd4pe.lab.albatrossflavour.com"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "scm.lab.albatrossflavour.com"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "dashboard.lab.albatrossflavour.com"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "smarthome.pdlf.net"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "pdlf.net"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
