apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lab-dns-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lab-dns-sync-secret
    template:
      engineVersion: v2
      data:
        PIHOLE_PASSWORD: "{{ .PIHOLE_API_KEY }}"
        PUPPETDB_TOKEN: "{{ .PUPPETDB_TOKEN }}"
  dataFrom:
    - extract:
        key: lab-dns-sync
