---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    template:
      engineVersion: v2
      data:
        # Nextcloud app variables
        NEXTCLOUD_ADMIN_USER: &adminUser "{{ .NEXTCLOUD_ADMIN_USER }}"
        NEXTCLOUD_ADMIN_PASSWORD: &adminPassword "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        NEXTCLOUD_SECRET_KEY: &secretKey "{{ .NEXTCLOUD_SECRET_KEY }}"

        # Database variables
        NEXTCLOUD_DB_PASSWORD: &dbPass "{{ .NEXTCLOUD_DB_PASSWORD }}"

        # Postgres Init variables
        INIT_POSTGRES_DBNAME: &dbName nextcloud
        INIT_POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbUser nextcloud
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: cloudnative-pg
