apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:fXy4BAry0MfJPnu0RhR1H2rLD6bYDK+EZLx9CSvM9WP/eWfe,iv:hbyDa/zbBETPvAd6+LODNQFXCaHLcGcg/OFQ4ZO6LKI=,tag:JzMGMtjdvyn4qjJUpz2aOA==,type:str]
    credentials.json: ENC[AES256_GCM,data:vNwTMQVbuGTOpZ7oHEFi0qnYYNBaYKg3iXu8sySgHir7vXI11z6362Ev9iSgBERPhzI2N9cVhfi5CFcHBhVXg6aHSp14XpAoFH0gabPRXmjii3DQswH2eX8jHJ3Rl3fYcRM6UWgIToVAewmNJs0/wlzYUS3IvfYhKVA/jBSZUGU1CKKD9/4xh43E0DXC9piHKguPY1CkLFQwmjq/2ahkjQEdolpUOoO/dZg68DA/Xw==,iv:mvZhQLdctNp/b2BDhNGZktShm9t20o43VpsEQmcvDy8=,tag:f7aDC5cZwtZIHTlvldvgnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7n73hztvwkq43gskmeddawn5w638dh30g0jycfxvn4h7ek9yvfq8tesqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIY2h1eFN0UUFoNzZUQmZW
            cXhDNzU4V0JUL1BtSVZwL2ZmaFFobEZMTUVzCmFpVVlpVUZIM3c0U1Q5Z2hyRURm
            T0w4QXYxd2FxZmZ6U0xPcXZZa092MlUKLS0tIDV6N2dBb01PMVlCeUo5ZTNoWFlz
            MHg4MkUwR2F4ZXdvVURKai9kK0JVaUkKtMT182Tloi5tV5ZaaX8XhWkwVVbGv85x
            TOuIK1Yzv7tOKEbaE+jkzIs3HOxKmOmtejhjxQ6qOTkpzQjBaURyjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T00:52:14Z"
    mac: ENC[AES256_GCM,data:MP2Tg/MkHdOBxgQcylkEgKnGISGWZeaDUQfiS2qbDAa3+BqLFR2PT20+weMq5o8rKkPz8bEf/pp1EMyqrOHReOM3+WWVRuI8+GEZN7ai7zwSsDALgEu+ur4t2OFHhnPZd9QH4Lj1RZdnoZEqDtzX1E9K3pOL4Nq7Dibu2nzrLBA=,iv:830df5VLlN577WjZ514VIwF6896x+z9n25uIXnylk0c=,tag:bafUdTzTKaCL8wbWcSNFeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
