apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wTaFiCfgd7A/N0s4b6aFpGqt2a/KfAp3BRCo+UaOxYolniPp,iv:j2Z5HV2KSrg1gjhKyIB+rPjuUGF4dLqSCNSOBhjIxA4=,tag:OiIOR+qc7L5figE4Nyf1wg==,type:str]
    credentials.json: ENC[AES256_GCM,data:xmKi5wYBcdIUiGVFMF1J35GBLhkDtfXy+2Y2w0Vj4RLRJnLcG6WTPqXi30ykBFGbr5SnModLud28reKIvtPZ0QCwyykTgdL1giPmYWsb6UiQGkcImM8BlpcaJ9O8wZzarFbNM1IKDr+CgSJl1QcO8jWbkbzzzdkrCLQCV9OTJP9cyUt9r1prCURBtmYlQjw1MH81qGREw2Eq+vnwirqwXUvamigDwL8Mt+x8WaEw/A==,iv:Vtd/1jHPUYShyJjH4v7wgWoKjJhAZ4vT+nSsSipCW5U=,tag:DmY0tUJj4tPn9qIkjYf4Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7n73hztvwkq43gskmeddawn5w638dh30g0jycfxvn4h7ek9yvfq8tesqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa0FoMDBQT2dUOW9OSFFX
            NHlJUFVQdWcwVFJzeVREeWMvWFZvaDJtODFFCkxLUmlJTHM0NUxTOUI0WHFqZ3ZQ
            NTJJZ1NBU3dIUVVpNnMyT2l3Vjg0MUUKLS0tIGMvanVjRWNVa0o2V1dhWU9qUUVV
            Y0t2aS9KaElGbkU3RUE3Sk1PTXZVcGMK0vmi54hCRCda0ng2Kb3VHwROyCYvDJZa
            HuG4HzvfTiIXWf3Bvo4l09b8JZjwEQ4mTc55q5BshH1VtraoEIeFUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T22:38:52Z"
    mac: ENC[AES256_GCM,data:ExjvGcmqGvtRpzzg3QOt3kOP/paXVoCrnl/5aFhhSyJBTue5PTWH7MeSlwZwPQ31qCdmDbBldAjJRBKFLMDhH40Tw0n7WUJFFGRiLRfH28ovm/eBF5OHYq1i492IDmOqnipEQY1P4JMbpI7Y5rPZI3pg/HNJk3thb91+p7i9+zQ=,iv:dYrwy2k9X7A3eA00+3MMJPRbgTahX2xgN0kbLrB8Oqg=,tag:qGU6fgOnBvSucz2tPRQJKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
