---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: atuin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ATUIN_DB_URI: "postgres://{{ .ATUIN_DATABASE_USER }}:{{ .ATUIN_DATABASE_PASS }}@{{ .POSTGRES_HOST }}:{{ .POSTGRES_PORT }}/{{ .ATUIN_DATABASE_NAME }}"
        # Postgres Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: "{{ .ATUIN_DATABASE_NAME }}"
        INIT_POSTGRES_USER: "{{ .ATUIN_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .ATUIN_DATABASE_PASS }}"
        INIT_POSTGRES_PORT: "{{ .POSTGRES_PORT }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: ATUIN
    - extract:
        key: CLOUDNATIVE_PG
