---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-fixable-check
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-fixable-check
rules:
  - apiGroups: ["aquasecurity.github.io"]
    resources: ["vulnerabilityreports"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-fixable-check
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-fixable-check
subjects:
  - kind: ServiceAccount
    name: trivy-fixable-check
    namespace: security
