{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "mqtt_temperature{endpoint=\"metrics\", topic!=\"zigbee2mqtt_0x00158d000ad5c1ce\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "mqtt_humidity{endpoint=\"metrics\", topic!=\"zigbee2mqtt_0x00158d000ad5c1ce\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Betty",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "kiln_target", "legendFormat": "Target" },
    { "expr": "kiln_temp", "legendFormat": "Temp" },
    { "expr": "kiln_time_remaining", "legendFormat": "Time Remaining" },
    {
     "expr": "node_hwmon_temp_celsius{instance=\"10.10.20.208:9100\", sensor=\"temp0\"}",
     "legendFormat": "Pi temp"
    }
   ]
  }
 ]
}