{
 "title": "Puppet Node Detail",
 "description": "Detailed information about individual Puppet nodes",
 "tags": [ "puppet" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "host",
    "label": "Server",
    "query": {
     "query": "label_values(puppet_report_timestamp_epoch,host)"
    }
   },
   { "name": "interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "puppetserver",
    "label": "Puppet Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,puppet_server)"
    }
   },
   {
    "name": "scmserver",
    "label": "SCM Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,scm_server)"
    }
   },
   {
    "name": "cd4peserver",
    "label": "CD4PE Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,cd4pe_server)"
    }
   },
   {
    "name": "grafanaserver",
    "label": "Grafana Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,grafana_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Patches Outstanding",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_patching_data{node=\"$host\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Patching Blocked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_patching_blocked{node=\"${host}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Restart Required",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_restart_required{type=\"app\",node=\"${host}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reboot Required",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_restart_required{type=\"reboot\",node=\"${host}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "noop Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_noop{host=\"$host\"}",
     "legendFormat": "No-Op mode"
    }
   ]
  },
  {
   "title": "CIS Scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (node,score_type) (puppet_cis_compliance_score{node=\"$host\"})",
     "legendFormat": "{{score_type}}"
    }
   ]
  },
  { "title": "Last Puppet Report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Time since last report",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-puppet_report_timestamp_epoch{host=~\"${host}\"}"
    }
   ]
  },
  {
   "title": "Total of Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_events{host=\"$host\",name=\"Total\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_events{name=\"Failure\",host=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_events{host=\"$host\",name=\"Success\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_resources{name=\"Total\",host=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Changes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "puppet_report_changes{host=\"$host\"}"
    }
   ]
  },
  { "title": "Last Puppet Run Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Duration (latest report)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(7,puppet_report_time{host=\"$host\",name!~\"(Total|Catalog application|Transaction evaluation)\"} > - 1)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources by status (latest report)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "puppet_report_resources{host=\"$host\",name!~\"(Total|Out of sync)\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Puppet Reports over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Resource Application Time",
   "type": "heatmap",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "puppet_report_time{host=\"$host\",name!~\"(Total|Catalog application|Transaction evaluation)\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources by status (over time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "puppet_report_resources{host=\"$host\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duration (over time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "puppet_report_time{name=~\"Config retrieval|Total\",host=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}