{
 "title": "Puppet Overview",
 "description": "Overview of your Puppet Enterprise estate",
 "tags": [ "puppet" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(puppet_report_timestamp_epoch,environment)"
    }
   },
   {
    "name": "puppetserver",
    "label": "Puppet Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,puppet_server)"
    }
   },
   {
    "name": "domain",
    "query": {
     "query": "label_values(puppet_infrastructure_config,domains)"
    }
   },
   {
    "name": "scmserver",
    "label": "SCM Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,scm_server)"
    }
   },
   {
    "name": "cd4peserver",
    "label": "CD4PE Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,cd4pe_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State Overview",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(puppet_state_overview[$__interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Servers In Puppet Enterprise",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_node_count{environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources Enforced",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_report_resources{name=\"Total\",environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Patches Outstanding",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_patching_data{type=\"all\",environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Infra Assistant Token Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "puppet_infra_assistant_tokens_total",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Servers In noop Mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(puppet_noop{environment=~\"${environment:regex}\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending noop Changes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_noop_pending{environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Puppet Agent Versions",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (puppet_version{environment=~\"${environment:regex}\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 } },
  {
   "title": "Changes Enforced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(puppet_report_resources{name=\"Failed\",environment=~\"${environment:regex}\"})",
     "legendFormat": "Failures"
    },
    {
     "expr": "sum(puppet_report_resources{name=\"Changed\", environment=~\"${environment:regex}\"})\n-\nsum(puppet_report_resources{name=\"Corrective change\", environment=~\"${environment:regex}\"})",
     "legendFormat": "Intentional Changes"
    },
    {
     "expr": "sum(puppet_report_resources{name=\"Corrective change\",environment=~\"${environment:regex}\"})",
     "legendFormat": "Corrective Changes"
    }
   ]
  },
  {
   "title": "Roles",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (role) (puppet_node_trusted{environment=~\"${environment:regex}\"}))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Status Overview",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "puppet_state_overview{state=\"unchanged\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "puppet_state_overview{state=\"intentional\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "puppet_state_overview{state=\"corrective\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "puppet_state_overview{state=\"failed\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "puppet_state_overview{state=\"noop\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "puppet_state_overview{state=\"unknown\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Servers Per Data Centre",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (datacenter) (puppet_node_trusted{environment=~\"${environment:regex}\"}))",
     "legendFormat": "{{datacenter}}"
    }
   ]
  },
  {
   "title": "Resources Under Enforcement",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(puppet_report_resources{name=\"Total\",environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Types",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum by (name,version) (puppet_node_os{environment=~\"${environment:regex}\"}))",
     "legendFormat": "{{name}} {{version}}"
    }
   ]
  },
  {
   "title": "Active Config Versions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by (version) (\n    puppet_configuration_version{environment=~\"${environment:regex}\", version!=\"\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}