{
 "title": "Patching Status",
 "description": "Fleet patching status using Puppet Enterprise",
 "tags": [ "puppet" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "patchgroup",
    "label": "Patch Group",
    "query": {
     "query": "label_values(puppet_patching_data,patch_group)"
    }
   },
   {
    "name": "datacenter",
    "label": "Data Centre",
    "query": {
     "query": "label_values(puppet_node_trusted,datacenter)"
    }
   },
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(puppet_node_trusted,role)"
    }
   },
   {
    "name": "domain",
    "label": "DNS Domain",
    "query": {
     "query": "label_values(puppet_node_os,node)"
    }
   },
   {
    "name": "puppetserver",
    "label": "Puppet Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,puppet_server)"
    }
   },
   {
    "name": "scmserver",
    "label": "SCM Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,scm_server)"
    }
   },
   {
    "name": "cd4peserver",
    "label": "CD4PE Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,cd4pe_server)"
    }
   },
   {
    "name": "grafanaserver",
    "label": "Grafana Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,grafana_server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Servers To Be Patched",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(puppet_patching_data{type=\"all\",patch_group=~\"${patchgroup:regex}\"} > 0) or vector(0)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_vrs_vulnerabilities_total)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "All Patches Outstanding",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_patching_data{type=\"all\",patch_group=~\"${patchgroup:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security Patches Outstanding",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_patching_data{type=\"security\",patch_group=~\"${patchgroup:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Patching Blocked",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(puppet_patching_blocked{patch_group=~\"${patchgroup:regex}\"} > 0)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fleet Wide Restart Requirements",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( count(puppet_restart_required{type=\"reboot\"} > 0) )\n/\n( count(puppet_restart_required{type=\"reboot\"}) )\n* 100",
     "legendFormat": "Server"
    },
    {
     "expr": "( count(puppet_restart_required{type=\"app\"} > 0) )\n/\n( count(puppet_restart_required{type=\"app\"}) )\n* 100",
     "legendFormat": "Application"
    }
   ]
  },
  {
   "title": "Patch Group Overview",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_patching_groups{patch_group=~\".+\"}",
     "legendFormat": "{{patch_group}}"
    }
   ]
  },
  {
   "title": "Top 10 Clients To Patch",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(puppet_patching_data{type=\"all\",patch_group=~\"${patchgroup:regex}\"} > 0)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Fleet Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Overview ",
   "type": "status-history",
   "gridPos": { "h": 17, "w": 20, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max by (node) (\n  puppet_patching_data{type=\"all\", patch_group=~\"${patchgroup:regex}\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Fleet Patching Status - All Patches",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(puppet_patching_data{type=\"all\",patch_group=~\"${patchgroup:regex}\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fleet Patching Status - Security Only",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 52 },
   "targets": [
    {
     "expr": "sum(puppet_patching_data{type=\"security\",patch_group=~\"${patchgroup:regex}\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}