{
 "title": "Puppet Overview V1",
 "description": "Overview of your Puppet Enterprise estate",
 "tags": [ "puppet" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(puppet_report_timestamp_epoch,environment)"
    }
   },
   {
    "name": "puppetserver",
    "label": "Puppet Server",
    "query": {
     "query": "label_values(puppet_server_used,instance)"
    }
   },
   {
    "name": "domain",
    "query": {
     "query": "label_values(puppet_server_used,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Servers In Puppet Enterprise",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_node_count{environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resources Enforced",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_report_resources{name=\"Total\",environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Puppet Agent Versions",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (puppet_version{environment=~\"${environment:regex}\"})",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Servers In noop Mode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(puppet_noop{environment=~\"${environment:regex}\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending noop Changes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_noop_pending{environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Changes Enforced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(puppet_report_resources{name=\"Failed\",environment=~\"${environment:regex}\"})",
     "legendFormat": "Failures"
    },
    {
     "expr": "sum(puppet_report_resources{name=\"Corrective change\",environment=~\"${environment:regex}\"}) - sum(puppet_report_resources{name=\"Changed\",environment=~\"${environment:regex}\"}) - sum(puppet_report_resources{name=\"Failed\",environment=~\"${environment:regex}\"})",
     "legendFormat": "Intentional Changes"
    },
    {
     "expr": "sum(puppet_report_resources{name=\"Corrective change\",environment=~\"${environment:regex}\"})",
     "legendFormat": "Corrective Changes"
    }
   ]
  }
 ]
}