{
 "title": "Puppet CIS Compliance",
 "tags": [ "puppet" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "benchmark",
    "label": "CIS Benchmark",
    "query": {
     "query": "label_values(puppet_cis_compliance_score,benchmark)"
    }
   },
   {
    "name": "level",
    "label": "Level",
    "query": {
     "query": "label_values(puppet_cis_compliance_score,profile)"
    }
   },
   {
    "name": "puppetserver",
    "label": "Puppet Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,puppet_server)"
    }
   },
   {
    "name": "scmserver",
    "label": "SCM Server",
    "query": {
     "query": "label_values(puppet_infrastructure_config,scm_server)"
    }
   },
   {
    "name": "type",
    "label": "Score Type",
    "query": {
     "query": "label_values(puppet_cis_compliance_score,score_type)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(puppet_cis_compliance_score,environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Compliance Average Fleet Wide",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(puppet_cis_compliance_score{score_type=\"base\",environment=~\"$environment\"})",
     "legendFormat": "Actual"
    },
    {
     "expr": "avg(puppet_cis_compliance_score{score_type=\"adjusted\",environment=~\"$environment\"})",
     "legendFormat": "With exceptions"
    }
   ]
  },
  {
   "title": "Unscanned Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(puppet_node_count{environment=\"all\"}) - count(puppet_cis_compliance_score{score_type=\"base\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last scan times",
   "type": "table",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(puppet_cis_compliance_score{environment=~\"$environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Least Compliant Servers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(bottomk(5,puppet_cis_compliance_score{benchmark=~\"$benchmark\",profile=~\"$level\",score_type=~\"$type\",environment=~\"$environment\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Most Compliant Servers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,puppet_cis_compliance_score{benchmark=~\"$benchmark\",profile=~\"$level\",score_type=~\"$type\",environment=~\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CIS Compliance Levels",
   "type": "heatmap",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (node,benchmark,profile,environment,score_type) (\n  puppet_cis_compliance_score{benchmark=~\"$benchmark\",profile=~\"$level\",score_type=~\"$type\",environment=~\"$environment\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}