{
 "title": "Puppet Node Detail V1",
 "description": "Detailed information about individual Puppet nodes",
 "tags": [ "puppet" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Server",
    "query": {
     "query": "label_values(puppet_report_timestamp_epoch,host)"
    }
   },
   { "name": "interval", "query": "30m,1h,6h,12h,1d,7d,14d,30d" },
   {
    "name": "puppetserver",
    "label": "Puppet Server",
    "query": {
     "query": "label_values(puppet_server_used,instance)"
    }
   },
   {
    "name": "domain",
    "query": {
     "query": "label_values(puppet_server_used,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Puppet Report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time since last report",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-puppet_report_timestamp_epoch{host=~\"${host}\"}"
    }
   ]
  },
  {
   "title": "Total of Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_events{host=\"$host\",name=\"Total\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_events{name=\"Failure\",host=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_events{host=\"$host\",name=\"Success\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_report_resources{name=\"Total\",host=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Changes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "puppet_report_changes{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "noop Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "puppet_noop{host=\"$host\"}",
     "legendFormat": "No-Op mode"
    }
   ]
  },
  {
   "title": "Last Puppet Run Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Duration (latest report)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(7,puppet_report_time{host=\"$host\",name!~\"(Total|Catalog application|Transaction evaluation)\"} > - 1)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources by status (latest report)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "puppet_report_resources{host=\"$host\",name!~\"(Total|Out of sync)\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Puppet Reports over time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Resource Application Time",
   "type": "heatmap",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "puppet_report_time{host=\"$host\",name!~\"(Total|Catalog application|Transaction evaluation)\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources by status (over time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "puppet_report_resources{host=\"$host\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Duration (over time)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "puppet_report_time{name=~\"Config retrieval|Total\",host=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}