{
 "title": "Thanos Overview",
 "description": "This dashboard provides a resource usage overview of the Thanos components Query, Compactor and Store Gateway. Modified for Bitnami Helm chart container names.",
 "tags": [ "thanos" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![logo](https://repository-images.githubusercontent.com/109162639/97e49180-661b-11e9-9882-fdc44b74debd)"
   }
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\".*thanos.*\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Thanos / Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"query\",pod=~\"thanos-query.*\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"query\",pod=~\"thanos-query.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-query.*\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"query\",pod=~\"thanos-query.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-query.*\"}",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Compactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"compactor\",pod=~\"thanos-compactor.*\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"compactor\",pod=~\"thanos-compactor.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-compactor.*\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"compactor\",pod=~\"thanos-compactor.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-compactor.*\"}",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Store Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Core Usage vs. Requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_spec_cpu_shares{container=\"storegateway\",pod=~\"thanos-storegateway.*\"}) by (pod) / 1000",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"storegateway\",pod=~\"thanos-storegateway.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(container_spec_memory_limit_bytes{pod=~\"thanos-storegateway.*\"}) by (pod)",
     "legendFormat": "{{pod}} (limit)"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"storegateway\",pod=~\"thanos-storegateway.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-storegateway.*\"}",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  }
 ]
}