---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-oci-auth
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: github-oci-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .GITHUB_USER }}",
                "password": "{{ .GITHUB_TOKEN }}"
              }
            }
          }
  dataFrom:
    - extract:
        key: github-oci
