# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shlink
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: shlink-secret
    template:
      engineVersion: v2
      data:
        # Shlink Database Configuration
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DB_NAME: &dbName shlink
        DB_USER: &dbUser shlink
        DB_PASSWORD: &dbPass "{{ .SHLINK_DB_PASSWORD }}"

        # Shlink Application Configuration
        INITIAL_API_KEY: "{{ .SHLINK_API_KEY }}"

        # Database Init Configuration
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: shlink
    - extract:
        key: cloudnative-pg
