---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shlink
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: shlink-secret
    template:
      engineVersion: v2
      data:
        # App
        DB_NAME: &dbName "{{ .SHLINK_DATABASE_NAME }}"
        DB_HOST: &dbHost "{{ .POSTGRES_HOST }}"
        DB_PORT: &dbPort "{{ .POSTGRES_PORT }}"
        DB_USER: &dbUser "{{ .SHLINK_POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .SHLINK_POSTGRES_PASS }}"
        DB_DRIVER: postgres
        GEOLITE_LICENSE_KEY: "{{ .LICENSE_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_PORT: *dbPort
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: maxmind
    - extract:
        key: shlink
    - extract:
        key: cloudnative-pg
