apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-reverse-proxy-config
  namespace: default
data:
  nginx.conf: |
    events { }

    http {
        server {
            listen 80;
            server_name dancer.${SECRET_DOMAIN};

            location / {
                proxy_pass http://192.168.1.22:5001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
