---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-reverse-proxy
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      nginx-reverse-proxy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: nginx
              tag: latest
            volumeMounts:
              - name: nginx-config-volume
                mountPath: /etc/nginx/nginx.conf
                subPath: nginx.conf
    volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-reverse-proxy-config
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: nginx-reverse-proxy
        ports:
          http:
            port: 80
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        className: external
        hosts:
          - host: dancer.solutions
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
