apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-reverse-proxy
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
spec:
  interval: 5m
  releaseName: nginx-reverse-proxy
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      ingressClassResource:
        name: external
        default: false
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - host: dancer.solutions
          paths: ["/"]
    extraVolumes:
      - name: proxy-config
        configMap:
          name: nginx-reverse-proxy-config
    extraVolumeMounts:
      - name: proxy-config
        mountPath: /etc/nginx/conf.d
        subPath: nginx.conf
    service:
      type: ClusterIP
      port: 80
