apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-reverse-proxy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    service:
      app:
        serviceName: nginx-reverse-proxy
        type: ClusterIP
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          className: external
        hosts:
          - host: dancer.solutions
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    defaultBackend:
      enabled: false
