---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-reverse-proxy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.0 # Specify the version you want to use
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-repo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controller:
      config:
        proxy-body-size: "64m"
        use-proxy-protocol: "true"
      service:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        className: external
    defaultBackend:
      enabled: false
    extraVolumeMounts:
      - name: custom-nginx-template
        mountPath: /etc/nginx/template/custom.tmpl
        subPath: custom.tmpl
    extraVolumes:
      - name: custom-nginx-template
        configMap:
          name: nginx-reverse-proxy-config
