---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-reverse-proxy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 19.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    image:
      registry: docker.io
      repository: bitnami/nginx
      tag: 1.27.4-debian-12-r5
    pullPolicy: IfNotPresent
    debug: false
    replicaCount: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate: {}
    serverBlock: |-
      server {
        listen 8080;
        server_name www.bandcamp.tv bandcamp.tv;
        return 301 $scheme://albatrossflavour.com;
      }

      server {
        listen 8080;
        server_name www.toodlepip.com.au toodlepip.com.au;
        return 301 $scheme://www.etsy.com/au/shop/ToodlepipdesignsAU;
      }

      server {
        listen 8080;
        server_name www.kalooma.org kalooma.org;
        return 301 $scheme://youtube.com/pdlfeggs;
      }

      server {
        listen 8080;
        server_name puppet.lab.albatrossflavour.com;
        ssl_verify_client off;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass https://192.168.7.10;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_buffer_size 128k;
          proxy_buffers 4 256k;
          proxy_busy_buffers_size 256k;
        #large_client_header_buffers 4 16k;
        }
      }

      server {
        listen 8080;
        server_name cd4pe.lab.albatrossflavour.com;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass https://192.168.7.11;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_buffer_size 128k;
          proxy_buffers 4 256k;
          proxy_busy_buffers_size 256k;
          #large_client_header_buffers 4 16k;
        }
      }


      server {
        listen 8080;
        server_name dashboard.lab.albatrossflavour.com;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass http://192.168.7.13;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_buffer_size 128k;
          proxy_buffers 4 256k;
          proxy_busy_buffers_size 256k;
          #large_client_header_buffers 4 16k;
        }
      }

      server {
        listen 8080;
        server_name smarthome.pdlf.net;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass http://192.168.1.223:8123;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_buffer_size 128k;
          proxy_buffers 4 256k;
          proxy_busy_buffers_size 256k;
          #large_client_header_buffers 4 16k;
        }
      }


      server {
        listen 8080;
        server_name scm.lab.albatrossflavour.com;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $host;

          proxy_pass https://192.168.7.12;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_buffer_size 128k;
          proxy_buffers 4 256k;
          proxy_busy_buffers_size 256k;
          #large_client_header_buffers 4 16k;
        }
      }

    ingress:
      ingressClassName: "external"
      hostname: "/*"
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      extraHosts:
        - name: dancer.solutions
          path: /
      main:
        enabled: true
        ingressClassName: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: www.kalooma.org
            paths:
              - path: /
                pathType: Prefix
          - host: www.kalooma.org
            paths:
              - path: /
                pathType: Prefix
          - host: toodlepip.com.au
            paths:
              - path: /
                pathType: Prefix
          - host: www.toodlepipe.com.au
            paths:
              - path: /
                pathType: Prefix
          - host: www.bandcamp.tv
            paths:
              - path: /
                pathType: Prefix
          - host: bandcamp.tv
            paths:
              - path: /
                pathType: Prefix
          - host: puppet.lab.albatrossflavour.com
            paths:
              - path: /
                pathType: Prefix
          - host: cd4pe.lab.albatrossflavour.com
            paths:
              - path: /
                pathType: Prefix
          - host: scm.lab.albatrossflavour.com
            paths:
              - path: /
                pathType: Prefix
          - host: dashboard.lab.albatrossflavour.com
            paths:
              - path: /
                pathType: Prefix

          - host: smarthome.pdlf.net
            paths:
              - path: /
                pathType: Prefix

    persistence:
      data:
        enabled: false
        existingClaim: nginx-config

    service:
      ports:
        http: &port 8080
      type: ClusterIP
      main:
        ports:
          http:
            port: *port

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        cpu: 15m
        memory: 79M
