apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-reverse-proxy
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-reverse-proxy
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      version: "*"
  values:
    replicaCount: 1
    nginxConfig:
      serverName: dancer.solutions
      proxyPass: http://192.168.1.22:5001
