---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-nginx
  namespace: flux-system
spec:
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts/nginx
  ref:
    tag: 22.0.10@sha256:0265f65aec8654a998e89be7a2c7d00e43e5cd35bef6b5ce70dfca0c4d473d25
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
