---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-pve-exporter-morpork
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      prometheus-pve-exporter-morpork:
        containers:
          app:
            image:
              repository: prompve/prometheus-pve-exporter
              tag: "3.4.2@sha256:fcf041f0c24d1e27f73a019af2df5da384353b25d6b2f2e187568e5644bd38bf"
            env:
              TZ: "${TIMEZONE:=Etc/UTC}"
            envFrom:
              - secretRef:
                  name: prometheus-pve-exporter-morpork
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 200Mi
    persistence:
      config:
        type: secret
        name: prometheus-pve-exporter-morpork
        globalMounts:
          - path: /etc/prometheus/pve.yml
            subPath: pve.yml
            readOnly: true
    service:
      app:
        controller: prometheus-pve-exporter-morpork
        ports:
          metrics:
            protocol: HTTP
            port: 9221
    serviceMonitor:
      app:
        serviceName: prometheus-pve-exporter-morpork
        endpoints:
          - port: metrics
            scheme: http
            path: /pve
            params:
              target:
                - morpork.lab.albatrossflavour.com:8006
            interval: 60s
            scrapeTimeout: 30s
            metricRelabelings:
              - action: labeldrop
                regex: (pod)
              - action: replace
                sourceLabels: ["service"]
                targetLabel: instance
                replacement: "morpork"
