---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    pullPolicy: IfNotPresent
    debug: false
    replicaCount: 1
    updateStrategy:
      type: RollingUpdate
      rollingUpdate: {}
    serverBlock: |-
      server {
        listen 8080;
        server_name dancer.solutions;
        return 301 $scheme://www.etsy.com/au/shop/ToodlepipdesignsAU;
      }

    ingress:
      hostname: "/*"
      extraHosts:
        - name: dancer.solutions
          path: /
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: dancer.solutions
            paths:
              - path: /
                pathType: Prefix
#       tls:
#         - hosts:
#             - dancer.solutions
#           secretName: nginx

    persistence:
      data:
        enabled: false
        existingClaim: nginx-config

    service:
      ports:
        http: &port 8080
      type: ClusterIP
      main:
        ports:
          http:
            port: *port

    resources:
      requests:
        cpu: 15m
        memory: 79M
      limits:
        cpu: 15m
        memory: 79M

