---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: influxdb-secret
    template:
      engineVersion: v2
      data:
        # Admin User
        admin-password: "{{ .ADMIN_PASSWORD }}"
        admin-token: "{{ .ADMIN_TOKEN }}"
  dataFrom:
    - extract:
        key: influxdb
