apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:tODJQ+VRtduDOMu5tXlfE0yWjeb8kTkl9seUSn5dxRqB+DlMX0mW1g==,iv:GAm3DJyVSGNjaH7q6qLgyYVVpfWmkITw4yLPobg8XTs=,tag:z96j/G6seNGjBzO40rXN8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7n73hztvwkq43gskmeddawn5w638dh30g0jycfxvn4h7ek9yvfq8tesqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQmFqaXFXdVl5eDh3eUdF
            VUcwWkprTFpvUm94eFUzU29iOUYrdVh0Um1NCnBwWmdKaVdLRnhiNUR1SFV2Qkhv
            Z2dURXdQc1lwUFYyZnQxMmp4LzV3elEKLS0tIG94RXFzeUhQdmN0VnNJYStNRTh1
            ZWdDNkRyZGFQTFU5akNLTVFwMmU3TWcKIl4ttgMUNmeKoyiWRhER3cnIj3ImO5sM
            sHJA9GhQH0t0a75n42ZEqN4LrQWl71bEhTkTTRKPxRfzSkaQdq49fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T08:24:12Z"
    mac: ENC[AES256_GCM,data:2eSc48JX8BPN2Hkh8MYx4ERSyYGgyWwcuDwf2A5axfTFgXg31HeOPepuYT7B3IiyAqrOIFEKn8KMsk5A9LdZZOLzCcXLdgsLiIZEE4G6pjL8CrdLeseE0Q2T09Skdov0EvqR8w/cSk9zgfUTPwB6Of4dsxpP5vpKIPr/ItBW8jQ=,iv:icCBjlBU/FGElTrmhn9jkJEb+if+AndP7Ria38kAVWQ=,tag:K95FdGs4iU7zG7ifAqmwNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
