apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:SCQZQBu5w2uhLrWzNSpGcFLJ1ykwuWjHIQJa4XN3TnLFMKpVezb7PGaLBS1UaWPWr+hLF5E=,iv:ZmnKBEkUHv7DboYFd+GGxJEQHSQOpN8Pq1I9G9SnmGY=,tag:vOGTho+gtiHVgtY2lD5dMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdHgzRlFTeHZWVjZGRXN0
            NWFmS1lnSU5ORGhpRWVTY05Wa2Z5OXdaY2pzCktEbzkvVWU0MHlYVE9QaUk0V0Na
            NlRBTjZHRlZrRkZWeVNhbnhLRTEwVlEKLS0tIGsvOTZHMW5WdzVDVDh4WWRxelRE
            UG01bHdPbTdpNnpkMGFFOFNGaDYrdnMKHAwm86TdtE5fvv5mxbKac4XtOZcWAbNL
            iFcP0NMYPVQCxeVXPFVoE3MjXC+oBPqGdWIKM6IOv9HjVjiqIu3j9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7n73hztvwkq43gskmeddawn5w638dh30g0jycfxvn4h7ek9yvfq8tesqz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T04:23:09Z"
    mac: ENC[AES256_GCM,data:RLvY5qoCGlKPVh3HzQH3E9xjQPVmnvxcBeCEx8wnVSMgJC5mhWsnkoT40odnNoKJOehDzpcLBfonhjzz2w74pR0eHQrLM+SHVH5vtEu8YhNJWaPmIeNcD0Jl2lt0Wp2Ypkki4GXYxip7XAauSdwE+Zk3GF9zDTqbIyIv7gB0tls=,iv:cLLbopD3yE7Nc2huZJMNm9SK5/X52QLu2E4jl1+cjq8=,tag:XLrrlfKiQdCUcKh0XI/IIA==,type:str]
    version: 3.9.0
