---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jsoncrack
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      jsoncrack:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: docker.io/enmanuelmoreira/jsoncrack
              tag: v3.2.0@sha256:cfd257a13dec324fc0e29b76d778a5a02b8f3863e5c4fca6aa6f39da272d06d3
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
            resources:
              requests:
                cpu: 15m
                memory: 79Mi
              limits:
                memory: 79Mi
    service:
      app:
        controller: jsoncrack
        ports:
          http:
            port: 80
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Utilities
          gethomepage.dev/name: JSON Crack
          gethomepage.dev/icon: mdi-code-json
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
