---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app jackett
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 4
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controllers:
      *app :
        replicas: 1

        containers:
          *app :
            image:
              repository: linuxserver/jackett
              tag: "0.21.2943"
            env:
              PUID: "568"
              PGID: "568"
              TZ: ${TIMEZONE}
    service:
      main:
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: 9117
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: jackett
    resources:
      requests:
        cpu: 1m
        memory: 250Mi
      limits:
        memory: 500Mi
