---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scrypted
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: scrypted
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
    - name: home-assistant
      namespace: default
  values:
    controllers:
      scrypted:
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/scrypted
              tag: 0.141.0@sha256:c9e82faec2e27debeba03fd8d4bdb2aa53cdaf0f3f8aa77c04312a047db4c2ea
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      app:
        ports:
          http:
            port: &port 11080
            primary: true
          rebroadcast1:
            port: 34135
          rebroadcast2:
            port: 34136
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Automation
          gethomepage.dev/name: Scrypted
          gethomepage.dev/icon: scrypted.png
          gethomepage.dev/description: Video Management
        className: internal
        hosts:
          - host: scrypted.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
    persistence:
      config:
        existingClaim: scrypted
        globalMounts:
          - path: /server/volume
