---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: scrypted
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.3.0@sha256:5d4bd46aedfe2ecb6fc23be144e3576087d64c731eebdb70b3d6be29f3bce845
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
