# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
    template:
      engineVersion: v2
      data:
        # Loki authentication
        LOKI_S3_ACCESS_KEY_ID: ""
        LOKI_S3_SECRET_ACCESS_KEY: ""
  dataFrom:
    - extract:
        key: loki
