---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netboot
  namespace: flux-system
spec:
  targetNamespace: utilities
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    #- name: rook-ceph-cluster
  path: ./kubernetes/apps/utilities/netboot/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: *app
      # VOLSYNC_CAPACITY: 2Gi
      # VOLSYNC_ACCESSMODES: ReadWriteMany
      # VOLSYNC_STORAGECLASS: ceph-filesystem
      # VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
