---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app vaultwarden
  namespace: flux-system
  # labels:
  #   substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: utilities
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/utilities/vaultwarden/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  dependsOn:
    - name: external-secrets-stores
    - name: rook-ceph-cluster
    #- name: volsync
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: vaultwarden
      namespace: utilities
  interval: 30m
  retryInterval: 1m
  timeout: 3m
