---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-puppet-lab-endpoints
  labels:
    gatus.io/enabled: "true"
data:
  puppet-lab.yaml: |
    endpoints:
      - name: Puppet Enterprise
        url: "https://puppet.lab.albatrossflavour.com/"
        group: "Puppet Lab"
        description: "Infrastructure Automation"
        tags: ["puppet", "automation", "critical", "lab"]
        interval: 2m
        client:
          insecure: true
        conditions:
          - "[STATUS] < 400"
          - "[RESPONSE_TIME] < 5000"
        alerts:
          - type: pagerduty

      - name: CD4PE
        url: "https://cd4pe.lab.albatrossflavour.com/"
        group: "Puppet Lab"
        description: "Continuous Deployment"
        tags: ["puppet", "cicd", "automation", "lab"]
        interval: 2m
        client:
          insecure: true
        conditions:
          - "[STATUS] < 400"
          - "[RESPONSE_TIME] < 5000"
        alerts:
          - type: pagerduty

      - name: SCE
        url: "https://sce.lab.albatrossflavour.com/"
        group: "Puppet Lab"
        description: "Compliance Engine"
        tags: ["puppet", "compliance", "automation", "lab"]
        interval: 2m
        client:
          insecure: true
        conditions:
          - "[STATUS] < 400"
          - "[RESPONSE_TIME] < 5000"
        alerts:
          - type: pagerduty

      - name: Puppet Dashboard
        url: "https://dashboard.lab.albatrossflavour.com/"
        group: "Puppet Lab"
        description: "Infrastructure Dashboard"
        tags: ["puppet", "monitoring", "dashboard", "lab"]
        interval: 2m
        client:
          insecure: true
        conditions:
          - "[STATUS] < 400"
          - "[RESPONSE_TIME] < 5000"
        alerts:
          - type: pagerduty

      - name: Nessus
        url: "https://nessus.lab.albatrossflavour.com/"
        group: "Puppet Lab"
        description: "Vulnerability Scanner"
        tags: ["security", "vulnerability", "scanning", "lab"]
        interval: 5m
        client:
          insecure: true
        conditions:
          - "[STATUS] < 400"
          - "[RESPONSE_TIME] < 10000"
        alerts:
          - type: pagerduty
