---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app it-tools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      it-tools:
        containers:
          app:
            image:
              repository: corentinth/it-tools
              tag: latest
              pullPolicy: IfNotPresent
            env:
              TZ: "${TZ}"
            resources:
              requests:
                cpu: 10m
                memory: 24Mi
              limits:
                memory: 128Mi
    service:
      app:
        controller: it-tools
        ports:
          http:
            port: 80
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Utilities
          gethomepage.dev/name: IT Tools
          gethomepage.dev/icon: mdi-tools
        hosts:
          - host: &host "utils.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
