---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./grafana.yaml
  - ./blackbox-exporter.yaml
  - ./gatus.yaml
  - ./kube-prometheus-stack.yaml
