apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bxwDe7YblH1mKzwL,iv:t02Ol44Degqqk6gUFlmAe5nHDmgV2NoCA48Kj7d1ALE=,tag:HW5uWk2UhMRZ2u/qbGG+6A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ri3Q5VruLvTEPx5SF/rRZioRbvqCC2mtB7yS,iv:ACufc71xGAV3qrEjtkTYvzU+SM2jHeJp0Gp7/XYTP+8=,tag:aZP7rzncvs0VMR2JfVOeGQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:A6KKPRqo1h+DtzgH57JkTiGafLB2/w//u78tb024/NBDhRIN,iv:iYW0UXtpqernoR4h/6xZZ5V+DEJGOR4klcqlXhA8Jzw=,tag:8u76TjSqciVgxpN3pDtPpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7n73hztvwkq43gskmeddawn5w638dh30g0jycfxvn4h7ek9yvfq8tesqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMEluZFgvT0ExaFdaZk5i
            VHVJOS9UUDl4ZmZuM2wwdUNzYU8rQ1llS0R3CjZBQnlhZGJZMDlUK2txY0YyZHUz
            RWlwUWRQOXNsUHdYTURVOGltQkRuNW8KLS0tIE91ZWZnUjZiNHpJNnppUU4vb2Jy
            bExPYzZwSmxhWGU2VElPTUl4M3UxMHcK2B9ruwGc65fweH1BMyCIJX5Z04gDwXzC
            QU4d5eYU3FGmG/KDxCGKOKFo8Bulf6SF34Jbg2qLCWf1+DpaPvhRvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T08:24:12Z"
    mac: ENC[AES256_GCM,data:wzyEQhGAy66G/Wezs//hoj+gH2F8ZFtSP6tLdfsFRVcKxYz6sybrwhyA3EDIO5S76wvFVTiCmAteu2t0WaaP8PVrhd7ywLNQYCgEbhl87Vru/vCcWgFI9GWW/Wq7HS9Uy0gSA4O7iVdsjgWTt8SoE5wSmukiXmYK/Lub4DPUjhk=,iv:Nou1pBow/8BnbxR5i43nyuIZj9iwZineR1hM5PB3xGY=,tag:vrWhPJ6FsLORPSjKxH9Wnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
