apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:4j94W2Wucqu+7zMjA1zBdSabcuo=,iv:3vc0t0HW4oMKfcim5hp3OYQhijnQfdpmUat9QiCoLtM=,tag:cvwOrdKu27Ug8NFgZfLenw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:47cJ/3reXh42rWq8KE8FdPS8Zk6lTovDX1M6,iv:5Bb0g1PWk15YnAMaLtdi3FxbLe27uFtne1kvLS0tJoo=,tag:8evBIebUVYxRMyE2891D/w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:dC7k7AI2eppiwb/y6oY7zMktkTzqytl8zV7Mw4ZDhqAEWgnB,iv:D3wMdez+BlnecGcs6szQ99xbOaj5H/govkL0AchKbiU=,tag:csgW6fUcqYlzZHYbhiB08Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7n73hztvwkq43gskmeddawn5w638dh30g0jycfxvn4h7ek9yvfq8tesqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWWphakF3SkJUS0c3bEJG
            OEdKQ0Fib1l1MlE1Y2pma1lYb0VNUVNaVVUwCnpldlJuWWZHSHhIUzVxaElBWkhv
            ankyUWQ0Wm9sd3VlT1kwQXlaTHVqdlkKLS0tIFg3WWNKeXRZa2pRRU9JMUtrZDdm
            dDU2NUhFMVJqcEluclNGSXozRkVrZjgKyn1n3hOJvEhR/OFjXNCiZPo5DzCbYK6O
            L/VDs9VVj37DJzuoZo+tvuzvo7u4VlUb7R2rq/h95R5gKj/0+QXz3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-19T22:38:52Z"
    mac: ENC[AES256_GCM,data:TK2X114e2MnAAp2yyTtLlcSrCeIsNGl+1pP6YWIH6oHnSR+UyylEDPV/l4vmQ4/dGDQbu3uUL6fyjGwCqjf+ApH3SqrbsYavjo5PUHbvmQmj/Vx6XQSiqdhr2HaUebnD5tVaYhrgdVLMI/Rhj1hYosrABPB1ihKsC4MicrmiHX0=,iv:YrvIesoTbIiEdAXGl4iVbHHks0vWb3yQXnRDI0uJ5/o=,tag:aIGZGMYXSpdtUpn/j11AjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
