---
apiVersion: v1
kind: Service
metadata:
  name: cloudflare-exporter
  labels:
    app.kubernetes.io/name: cloudflare-exporter
spec:
  selector:
    app.kubernetes.io/name: cloudflare-exporter
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
