---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-exporter
  labels:
    app.kubernetes.io/name: cloudflare-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-exporter
  endpoints:
    - port: metrics
      interval: 1m
      scrapeTimeout: 30s
