---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nocodb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nocodb-secret
    template:
      engineVersion: v2
      data:
        # NocoDB configuration
        NOCODB_DB_PASSWORD: &dbPass "{{ .NOCODB_DB_PASSWORD }}"
        NC_AUTH_JWT_SECRET: "{{ .NC_AUTH_JWT_SECRET }}"
        NC_SENTRY_DSN: ""

        # Database configuration
        NC_DB: "pg://postgres16-rw.database.svc.cluster.local:5432?u=nocodb&p={{ .NOCODB_DB_PASSWORD }}&d=nocodb"

        # Postgres Init variables
        INIT_POSTGRES_DBNAME: &dbName nocodb
        INIT_POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbUser nocodb
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: nocodb
    - extract:
        key: cloudnative-pg
