---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-config
data:
  config.yaml: |
    metrics:
      - name: cluster_nodes
        category: Cluster
        description: Number of cluster nodes
        query: "count(kube_node_info)"
        suffix: ""
        colors:
          - { color: "red", min: 0, max: 0 }
          - { color: "orange", min: 1, max: 2 }
          - { color: "green", min: 3, max: 99 }

      - name: cluster_pods_running
        category: Cluster
        description: Number of running pods
        query: "sum(kube_pod_status_phase{phase=\"Running\"})"
        suffix: ""
        colors:
          - { color: "red", min: 0, max: 0 }
          - { color: "orange", min: 1, max: 49 }
          - { color: "green", min: 50, max: 9999 }

      - name: cluster_pods_unhealthy
        category: Cluster
        description: Number of unhealthy pods
        query: "sum(kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\"})"
        suffix: ""
        colors:
          - { color: "green", min: 0, max: 0 }
          - { color: "orange", min: 1, max: 5 }
          - { color: "red", min: 6, max: 9999 }

      - name: cluster_cpu_usage
        category: Resources
        description: Cluster CPU usage percentage
        query: "round((1 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))) * 100, 0.1)"
        suffix: "%"
        colors:
          - { color: "green", min: 0, max: 70 }
          - { color: "orange", min: 70, max: 85 }
          - { color: "red", min: 85, max: 100 }

      - name: cluster_memory_usage
        category: Resources
        description: Cluster memory usage percentage
        query: "round((1 - (avg(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))) * 100, 0.1)"
        suffix: "%"
        colors:
          - { color: "green", min: 0, max: 70 }
          - { color: "orange", min: 70, max: 85 }
          - { color: "red", min: 85, max: 100 }

      - name: cluster_storage_usage
        category: Resources
        description: Cluster storage usage percentage
        query: "round((1 - (avg(node_filesystem_avail_bytes{fstype!=\"tmpfs\"} / node_filesystem_size_bytes{fstype!=\"tmpfs\"}))) * 100, 0.1)"
        suffix: "%"
        colors:
          - { color: "green", min: 0, max: 70 }
          - { color: "orange", min: 70, max: 85 }
          - { color: "red", min: 85, max: 100 }

      - name: cluster_alerts_firing
        category: Alerts
        description: Number of firing alerts
        query: "sum(ALERTS{alertstate=\"firing\"})"
        suffix: ""
        colors:
          - { color: "green", min: 0, max: 0 }
          - { color: "orange", min: 1, max: 5 }
          - { color: "red", min: 6, max: 9999 }

      - name: cluster_alerts_pending
        category: Alerts
        description: Number of pending alerts
        query: "sum(ALERTS{alertstate=\"pending\"})"
        suffix: ""
        colors:
          - { color: "green", min: 0, max: 0 }
          - { color: "yellow", min: 1, max: 3 }
          - { color: "orange", min: 4, max: 9999 }
