---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kromgo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kromgo-secret
    template:
      engineVersion: v2
      data:
        # Add any sensitive Kromgo configuration here if needed
        KROMGO_CONFIG: "{{ .KROMGO_CONFIG | default \"{}\" }}"
  dataFrom:
    - extract:
        key: kromgo
