---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "kromgo"
        group: external
        url: "https://kromgo.${SECRET_DOMAIN}/cluster_nodes"
        interval: 1m
        ui:
          hide-hostname: true
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 5000"
        alerts:
          - type: pushover
