---
# yaml-language-server: $schema=https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/jsonschema/servicemonitor.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dragonfly
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
      app.kubernetes.io/component: dragonfly
  endpoints:
    - port: metrics
      scheme: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
