---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-metrics
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/component: dragonfly
spec:
  ports:
    - name: metrics
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: dragonfly
    app.kubernetes.io/name: dragonfly
