---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  monitor:
    desc: Monitor Cilium network policies for suspicious activity
    summary: |
      Checks Cilium logs for:
      - Denied/dropped traffic
      - Tor exit node connections
      - Suspicious VPN/proxy traffic
      - Recent policy activity

      Usage:
        task security:monitor           # Check last 1000 log lines
        task security:monitor -- 5000   # Check last 5000 log lines
    cmd: "{{.ROOT_DIR}}/scripts/monitor-cilium-threats.sh {{.CLI_ARGS}}"
    preconditions:
      - msg: Monitoring script not found
        sh: test -f {{.ROOT_DIR}}/scripts/monitor-cilium-threats.sh
      - msg: kubeconfig not found
        sh: test -f {{.ROOT_DIR}}/kubeconfig

  watch:
    desc: Watch Cilium threat monitor in real-time (refreshes every 30s)
    summary: |
      Continuously monitors Cilium logs for suspicious activity.
      Updates every 30 seconds. Press Ctrl+C to stop.
    cmd: watch -n 30 "{{.ROOT_DIR}}/scripts/monitor-cilium-threats.sh"
    preconditions:
      - msg: Monitoring script not found
        sh: test -f {{.ROOT_DIR}}/scripts/monitor-cilium-threats.sh
      - msg: kubeconfig not found
        sh: test -f {{.ROOT_DIR}}/kubeconfig
      - msg: watch command not found - install with 'brew install watch'
        sh: command -v watch

  policies:list:
    desc: List active Cilium network policies
    cmd: kubectl --kubeconfig {{.ROOT_DIR}}/kubeconfig get ciliumclusterwideNetworkpolicies,ciliumnetworkpolicies -A
    preconditions:
      - msg: kubeconfig not found
        sh: test -f {{.ROOT_DIR}}/kubeconfig

  policies:suspend:
    desc: Emergency suspend - disable all Cilium policies
    summary: |
      EMERGENCY USE ONLY - Suspends Flux kustomization for Cilium policies.
      This stops enforcement but does not delete existing policies immediately.

      To resume: task security:policies:resume
    prompt: This will suspend Cilium network policy enforcement. Continue?
    cmd: flux --kubeconfig {{.ROOT_DIR}}/kubeconfig suspend kustomization cilium-policies -n flux-system
    preconditions:
      - msg: kubeconfig not found
        sh: test -f {{.ROOT_DIR}}/kubeconfig

  policies:resume:
    desc: Resume Cilium policies after emergency suspension
    cmd: flux --kubeconfig {{.ROOT_DIR}}/kubeconfig resume kustomization cilium-policies -n flux-system
    preconditions:
      - msg: kubeconfig not found
        sh: test -f {{.ROOT_DIR}}/kubeconfig

  logs:live:
    desc: Stream live Cilium logs (filtered for policy activity)
    cmd: kubectl --kubeconfig {{.ROOT_DIR}}/kubeconfig logs -n kube-system -l k8s-app=cilium -f | grep -iE "(policy|denied|drop|tor|185\.220)"
    preconditions:
      - msg: kubeconfig not found
        sh: test -f {{.ROOT_DIR}}/kubeconfig
