---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Proxmox:
        - Ankh:
            - href: https://ankh.lab.albatrossflavour.com:8006
              icon: si-proxmox-#E57000
              siteMonitor: https://ankh.lab.albatrossflavour.com
        - Morpork:
            - href: https://morpork.lab.albatrossflavour.com:8006
              icon: si-proxmox-#E57000
              siteMonitor: https://morpork.lab.albatrossflavour.com
        - Stolat:
            - href: https://stolat.lab.albatrossflavour.com:8006
              icon: si-proxmox-#E57000
              siteMonitor: https://stolat.lab.albatrossflavour.com
        - Backups:
            - href: https://pbs.lab.albatrossflavour.com:8007
              icon: si-proxmox-#E57000
              siteMonitor: https://pbs.lab.albatrossflavour.com
    - Puppet:
        - Puppet Enterprise:
            - icon: si-puppet-#FFAE1A
              href: https://puppet.lab.albatrossflavour.com
              siteMonitor: https://puppet.lab.albatrossflavour.com
        - CD4PE:
            - icon: si-puppet-#FFAE1A
              href: https://cd4pe.lab.albatrossflavour.com
              siteMonitor: https://cd4pe.lab.albatrossflavour.com
        - SCM:
            - icon: si-puppet-#FFAE1A
              href: https://scm.lab.albatrossflavour.com
              siteMonitor: https://scm.lab.albatrossflavour.com
        - Dashboard:
            - icon: si-puppet-#FFAE1A
              href: https://dashboard.lab.albatrossflavour.com
              siteMonitor: https://dashboard.lab.albatrossflavour.com
        - control-repo:
            - icon: github.png
              href: 'https://github.com/albatrossflavour/control-repo'
    - Media:
        - overseerr:
            - icon: overseerr.png
              href: https://requests.albatrossflavour.com
        - sonarr:
            - icon: sonarr.png
              href: https://sonarr.albatrossflavour.com
        - radarr:
            - icon: radarr.png
              href: https://radarr.albatrossflavour.com
        - sabnzbd:
            - icon: sabnzbd.png
              href: https://sabnzbd.albatrossflavour.com
    - Git:
        - home-ops:
            - icon: github.png
              href: 'https://github.com/albatrossflavour/home-ops'
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: 'https://kubesearch.dev/'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Puppet:
        - Puppet Enterprise:
            - icon: si-puppet-#FFAE1A
              href: https://puppet.lab.albatrossflavour.com
              siteMonitor: https://puppet.lab.albatrossflavour.com
        - CD4PE:
            - icon: si-puppet-#FFAE1A
              href: https://cd4pe.lab.albatrossflavour.com
              siteMonitor: https://cd4pe.lab.albatrossflavour.com
        - SCM:
            - icon: si-puppet-#FFAE1A
              href: https://scm.lab.albatrossflavour.com
              siteMonitor: https://scm.lab.albatrossflavour.com
        - Dashboard:
            - icon: si-puppet-#FFAE1A
              href: https://dashboard.lab.albatrossflavour.com
              siteMonitor: https://dashboard.lab.albatrossflavour.com
        - control-repo:
            - icon: github.png
              href: 'https://github.com/albatrossflavour/control-repo'
    - Calendar:
        - Agenda:
            widget:
              type: calendar
              view: agenda # optional - possible values monthly, agenda
              maxEvents: 20 # optional - defaults to 10
              integrations: # optional
                - type: sonarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Sonarr # service name for that widget
                - type: radarr # active widget type that is currently enabled on homepage - possible values: radarr, sonarr>
                  service_group: Downloads # group name where widget exists
                  service_name: Radarr # service name for that widget
  settings.yaml: |
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    useEqualHeights: true
    theme: dark
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Network:
        style: row
        columns: 3
        icon: mdi-network
      Games:
        style: row
        columns: 3
        icon: mdi-minecraft
      Calendar:
        style: column
        icon: mdi-calendar
      Video:
        style: column
        icon: mdi-play-circle
      Books:
        style: row
        columns: 2
        icon: mdi-book
      Infrastructure:
        style: row
        columns: 5
        icon: mdi-server
      Observability:
        style: row
        columns: 5
        icon: mdi-chart-line
      Home:
        style: row
        columns: 5
        icon: mdi-home-analytics
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
  widgets.yaml: |
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Boomshanka!"
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - datetime:
        text_size: l
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
