---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
#   - Lab:
#       - Ankh:
#           - href: https://ankh.lab.albatrossflavour.com:8006
#             icon: si-proxmox-#E57000
#       - Morpork:
#           - href: https://morpork.lab.albatrossflavour.com:8006
#             icon: si-proxmox-#E57000
#       - Stolat:
#           - href: https://stolat.lab.albatrossflavour.com:8006
#             icon: si-proxmox-#E57000
#       - Backups:
#           - href: https://pbs.lab.albatrossflavour.com:8007
#             icon: si-proxmox-#E57000
#       - Ankh KVM:
#           - href: https://192.168.5.20/login/
#             icon: si-pikvm
#       - Morpork KVM:
#           - href: https://192.168.5.21/login/
#             icon: si-pikvm
#       - Stolat KVM:
#           - href: https://192.168.5.22/login/
#             icon: si-pikvm
#   - Infrastructure:
#       - Grafana:
#           - href: http://grafana.albatrossflavour.com
#             icon: si-grafana
#       - Pi-Hole:
#           - href: http://192.168.9.2/admin/login.php
#             icon: si-pihole
#       - Luggage:
#           - href: https://192.168.1.22:5006
#             icon: si-synology
#       - UniFi:
#           - href: https://192.168.1.1
#             icon: si-unifi
#   - Puppet:
#       - Puppet Enterprise:
#           - icon: si-puppet-#FFAE1A
#             href: https://puppet.lab.albatrossflavour.com
#             siteMonitor: https://puppet.lab.albatrossflavour.com
#       - CD4PE:
#           - icon: si-puppet-#FFAE1A
#             href: https://cd4pe.lab.albatrossflavour.com
#             siteMonitor: https://cd4pe.lab.albatrossflavour.com
#       - SCM:
#           - icon: si-puppet-#FFAE1A
#             href: https://scm.lab.albatrossflavour.com
#             siteMonitor: https://scm.lab.albatrossflavour.com
#       - Dashboard:
#           - icon: si-puppet-#FFAE1A
#             href: https://dashboard.lab.albatrossflavour.com
#             siteMonitor: https://dashboard.lab.albatrossflavour.com
#       - control-repo:
#           - icon: github.png
#             href: 'https://github.com/albatrossflavour/control-repo'
#   - Media:
#       - overseerr:
#           - icon: overseerr.png
#             href: https://requests.albatrossflavour.com
#       - sonarr:
#           - icon: sonarr.png
#             href: https://sonarr.albatrossflavour.com
#             widget:
#               type: sonarr
#               url: http://sonarr.albatrossflavour.com
#               key: f0834e84a4ec435a854733188f205ed0
#       - radarr:
#           - icon: radarr.png
#             href: https://radarr.albatrossflavour.com
#       - sabnzbd:
#           - icon: sabnzbd.png
#             href: https://sabnzbd.albatrossflavour.com
#   - Git:
#       - home-ops:
#           - icon: github.png
#             href: 'https://github.com/albatrossflavour/home-ops'
#       - kubesearch:
#           - icon: kubernetes-dashboard.png
#             href: 'https://kubesearch.dev/'
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Media:
      - sonarr:
          icon: sonarr.png
          href: http://sonarr.albatrossflavour.com/
          description: TV management
          widget:
            type: sonarr
            url: http://sonarr.albatrossflavour.com
            key: f0834e84a4ec435a854733188f205ed0
      - radarr:
          icon: radarr.png
          href: http://radarr.albatrossflavour.com/
          description: movie management
          widget:
            type: radarr
            url: http://radarr.albatrossflavour.com
            key: F2ZqCXJcbsEzwLbYJcvA
  settings.yaml: |
    title: Dashboard
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    useEqualHeights: true
    theme: dark
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Network:
        style: row
        columns: 3
        icon: mdi-network
      Games:
        style: row
        columns: 3
        icon: mdi-minecraft
      Calendar:
        style: column
        icon: mdi-calendar
      Video:
        style: column
        icon: mdi-play-circle
      Books:
        style: row
        columns: 2
        icon: mdi-book
      Infrastructure:
        style: row
        columns: 5
        icon: mdi-server
      Observability:
        style: row
        columns: 5
        icon: mdi-chart-line
      Home:
        style: row
        columns: 5
        icon: mdi-home-analytics
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
  widgets.yaml: |
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Boomshanka!"
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - datetime:
        text_size: l
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
