---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Lab:
        - Ankh:
            - href: https://ankh.lab.albatrossflavour.com:8006
              siteMonitor: https://ankh.lab.albatrossflavour.com:8006
              icon: si-proxmox-#E57000
              description: ""
        - Morpork:
            - href: https://morpork.lab.albatrossflavour.com:8006
              siteMonitor: https://morpork.lab.albatrossflavour.com:8006
              icon: si-proxmox-#E57000
              description: ""
        - Stolat:
            - href: https://stolat.lab.albatrossflavour.com:8006
              siteMonitor: https://stolat.lab.albatrossflavour.com:8006
              icon: si-proxmox-#E57000
              description: ""
        - Backups:
            - href: https://pbs.lab.albatrossflavour.com:8007
              icon: si-proxmox-#E57000
              description: ""
        - Ankh KVM:
            - href: https://192.168.5.20/login/
              icon: si-raspberrypi-#E57000
              description: ""
        - Morpork KVM:
            - href: https://192.168.5.21/login/
              icon: si-raspberrypi-#E57000
              description: ""
        - Stolat KVM:
            - href: https://192.168.5.22/login/
              icon: si-raspberrypi-#E57000
              description: ""
    - Puppet:
        - Puppet Enterprise:
            - icon: si-puppet-#FFAE1A
              href: https://puppet.lab.albatrossflavour.com
              siteMonitor: https://puppet.lab.albatrossflavour.com
              description: ""
        - CD4PE:
            - icon: si-puppet-#FFAE1A
              href: https://cd4pe.lab.albatrossflavour.com
              siteMonitor: https://cd4pe.lab.albatrossflavour.com
              description: ""
        - SCM:
            - icon: si-puppet-#FFAE1A
              href: https://scm.lab.albatrossflavour.com
              siteMonitor: https://scm.lab.albatrossflavour.com
              description: ""
        - Dashboard:
            - icon: si-puppet-#FFAE1A
              href: https://dashboard.lab.albatrossflavour.com
              siteMonitor: https://dashboard.lab.albatrossflavour.com
              description: ""
        - control-repo:
            - icon: si-github-#BCBDAC
              href: 'https://github.com/albatrossflavour/control-repo'
              description: ""
    - Git:
        - home-ops:
            - icon: si-github-#BCBDAC
              href: 'https://github.com/albatrossflavour/home-ops'
              description: ""
        - kubesearch:
            - icon: si-kubernetes-#BCBDAC
              href: 'https://kubesearch.dev/'
              description: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    ---
    - Infrastructure:
        - Pihole:
            href: http://192.168.9.2/admin/login.php
            icon: si-pihole-#BCBDAC
            description: ""
            widget:
              type: pihole
              url: http://192.168.9.2
              version: 6
              key: {{HOMEPAGE_VAR_PIHOLE_TOKEN}}
        - Unifi:
            href: https://192.168.1.1
            icon: mdi-wifi-#BCBDAC
            widget:
              type: unifi
              url: https://192.168.1.1
              username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
              password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
        - Luggage:
            href: https://192.168.1.22:5006
            icon: mdi-nas-#BCBDAC
            description: ""
    - Schedule:
        - Calendar:
            name: Media Calendar
            widget:
              type: calendar
              view: monthly
              maxEvents: 10
              showTime: true
              timezone: Australia/Sydney
              integrations:
                - type: sonarr
                  service_group: Media
                  service_name: Sonarr
                  params:
                    unmonitored: true
                - type: radarr
                  service_group: Media
                  service_name: Radarr
                  params:
                    unmonitored: true
    - Media:
  settings.yaml: |
    background:
      image: https://raw.githubusercontent.com/albatrossflavour/home-ops/master/kubernetes/apps/security/authentik/app/images/background.jpg
      blur: sm
      brightness: 20
      opacity: 20
    title: Dashboard
    favicon: https://raw.githubusercontent.com/albatrossflavour/home-ops/master/kubernetes/apps/security/authentik/app/images/favicon.ico
    useEqualHeights: true
    iconStyle: theme
    theme: dark
    color: slate
    headerStyle: clean
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      Automation:
        style: row
        columns: 4
        icon: mdi-home-automation
      Utilities:
        style: row
        columns: 4
        icon: mdi-tools
      Puppet:
        icon: si-puppet-#FFAE1A
        style: column
      Lab:
        icon: mdi-server
        style: column
      Git:
        icon: mdi-home-analytics
        style: column
      Observability:
        style: row
        columns: 3
        icon: mdi-chart-line
      Infrastructure:
        icon: mdi-home-analytics
        columns: 3
        style: row
      Downloads:
        style: row
        columns: 3
        icon: mdi-download-circle
      Schedule:
        style: row
        columns: 1
        icon: mdi-calendar
      Media:
        style: row
        columns: 4
        icon: mdi-play-network
  widgets.yaml: |
    - search:
        provider: [duckduckgo, google]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Boomshanka!"
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - datetime:
        locale: au
        text_size: l
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
