---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ## Downloads
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SABNZBD_TOKEN: "{{ .SABNZBD_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_PBS_USERNAME: "{{ .PBS_USERNAME }}"
        HOMEPAGE_VAR_PBS_TOKEN: "{{ .PBS_TOKEN }}"
        HOMEPAGE_VAR_OVERSEERR_TOKEN: "{{ .OVERSEERR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_TAUTULLI_TOKEN: "{{ .TAUTULLI_API_KEY }}"
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        HOMEPAGE_VAR_PIHOLE_TOKEN: "{{ .PIHOLE_API_KEY }}"
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .UP_UNIFI_DEFAULT_USER }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .UP_UNIFI_DEFAULT_PASS }}"

        ## New additions for missing applications
        HOMEPAGE_VAR_MINIO_USERNAME: "{{ .MINIO_ROOT_USER }}"
        HOMEPAGE_VAR_MINIO_PASSWORD: "{{ .MINIO_ROOT_PASSWORD }}"
        HOMEPAGE_VAR_HOME_ASSISTANT_TOKEN: "{{ .HOME_ASSISTANT_API_KEY }}"
        HOMEPAGE_VAR_N8N_API_KEY: "{{ .N8N_API_KEY }}"
        HOMEPAGE_VAR_AUTHENTIK_API_KEY: "{{ .AUTHENTIK_API_KEY }}"
        HOMEPAGE_VAR_PAPERLESS_USERNAME: "{{ .paperless_admin_username }}"
        HOMEPAGE_VAR_PAPERLESS_PASSWORD: "{{ .paperless_admin_password }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: sabnzbd
    - extract:
        key: sonarr
    - extract:
        key: pbs
    - extract:
        key: prowlarr
    - extract:
        key: overseerr
    - extract:
        key: tautulli
    - extract:
        key: qbittorrent
    - extract:
        key: pihole
    - extract:
        key: grafana
    - extract:
        key: unpoller
    - extract:
        key: minio
    - extract:
        key: home-assistant
    - extract:
        key: n8n
    - extract:
        key: authentik
    - extract:
        key: paperless
