---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    template:
      engineVersion: v2
      data:
        # Application secrets
        DB_PASSWORD: &dbPass "{{ .IMMICH_DB_PASSWORD }}"
        JWT_SECRET: "{{ .IMMICH_JWT_SECRET }}"

        # Postgres Init variables
        INIT_POSTGRES_DBNAME: &dbName immich
        INIT_POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbUser immich
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
