---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-nfs
spec:
  storageClassName: frigate-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.22
    path: /volume2/frigate
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: frigate-nfs
  resources:
    requests:
      storage: 1Mi
