---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: linkwarden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DATABASE_URL: "postgres://{{ .LINKWARDEN_DATABASE_USER }}:{{ .LINKWARDEN_DATABASE_PASS }}@{{ .POSTGRES_HOST }}:{{ .POSTGRES_PORT }}/{{ .LINKWARDEN_DATABASE_NAME }}"
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        # Authentik
        AUTHENTIK_ISSUER: "{{ .OIDC_ISSUER }}"
        AUTHENTIK_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_PORT: "{{ .POSTGRES_PORT }}"
        INIT_POSTGRES_DBNAME: "{{ .LINKWARDEN_DATABASE_NAME }}"
        INIT_POSTGRES_USER: "{{ .LINKWARDEN_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .LINKWARDEN_DATABASE_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: LINKWARDEN
    - extract:
        key: CLOUDNATIVE_PG
