---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app linkwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          secret.reloader.stakater.com/reload: &secret linkwarden-secret
        initContainers:
          init-db:
            image:
              repository: docker.io/enmanuelmoreira/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: *secret
        containers:
          main:
            image:
              repository: ghcr.io/linkwarden/linkwarden
              tag: v2.7.1
            env:
              TZ: America/Santiago
              NEXTAUTH_URL: https://linkwarden.mapanare.net
              NEXT_PUBLIC_DISABLE_REGISTRATION: "true"
              NEXT_PUBLIC_AUTHENTIK_ENABLED: "true"
            envFrom: *envFrom
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 60
                  preference:
                    matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                          - amd64
                          - i386
                          - i686
                          - x86
    service:
      main:
        controller: main
        ports:
          http:
            enabled: true
            port: 3000
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host linkwarden.mapanare.net
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        storageClass: ceph-filesystem
        accessMode: ReadWriteMany
        size: 5Gi
        globalMounts:
          - path: /config
        retain: true
