---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "home-assistant-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "home-assistant"
        group: external
        url: "https://home-assistant.${SECRET_DOMAIN}"
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
