---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: infisical-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        JWT_SIGNUP_SECRET: "{{ .JWT_SIGNUP_SECRET }}"
        JWT_REFRESH_SECRET: "{{ .JWT_REFRESH_SECRET }}"
        JWT_AUTH_SECRET: "{{ .JWT_AUTH_SECRET }}"
        JWT_MFA_SECRET : "{{ .JWT_MFA_SECRET  }}"
        JWT_SERVICE_SECRET: "{{ .JWT_SERVICE_SECRET }}"
        # MONGODB
        # MONGO_URL: "mongodb://{{ .MONGODB_SUPER_USER }}:{{ .MONGODB_SUPER_PASS }}@{{ .MONGODB_HOST }}:{{ .MONGODB_PORT }}/{{ .MONGODB_NAME }}"
        # SMTP Options
        SMTP_HOST: "{{ .SMTP_SERVER }}"
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_FROM: "{{ .SMTP_USERNAME }}"
        SMTP_FROM_NAME: "{{ .SMTP_USERNAME }}"
        SMTP_PORT: "{{ .SMTP_PORT }}"

  dataFrom:
    - extract:
        key: INFISICAL
    # - extract:
    #     key: MONGODB
    - extract:
        key: SMTP
