---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app infisical
spec:
  interval: 30m
  chart:
    spec:
      chart: infisical
      version: 0.4.2
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  values:
    backend:
      enabled: true
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: &secret infisical-secret
      name: backend
      replicaCount: 2
      image:
        repository: docker.io/infisical/infisical
        tag: v0.43.19
        pullPolicy: IfNotPresent
    backendEnvironmentVariables:
      HTTPS_ENABLED: true
      INVITE_ONLY_SIGNUP: false
      SITE_URL: https://infisical.mapanare.net
    kubeSecretRef: *secret
    ## Mongo DB persistence
    mongodb:
      enabled: true
      name: "infisical-mongodb"
      fullnameOverride: "infisical-mongodb"
      useStatefulSet: true
      architecture: "standalone"
      image:
        repository: bitnami/mongodb
        tag: 7.0.14-debian-12-r3
        pullPolicy: IfNotPresent
      persistence:
        enabled: true
        size: 8Gi
        accessModes: ["ReadWriteOnce"]
    redis:
      #fullnameOverride: "infisical-redis"
      enabled: true
      architecture: standalone
      auth:
        enabled: false
    service:
      #annotations: {}
      type: ClusterIP
      nodePort: ""
    ingress:
      enabled: true
      ingressClassName: internal
      nginx:
        enabled: false
      #annotations: {}
      hostName: &host "infisical.mapanare.net"
      tls:
        - secretName: mapanare-net-tls
          hosts:
            - *host
