---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname stirling-pdf
  namespace: flux-system
spec:
  targetNamespace: utilities
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/utilities/stirling-pdf/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      GATUS_SUBDOMAIN: pdf
      VOLSYNC_CAPACITY: 5Gi
