apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:OuOsdwW/jpYHOrGixvBdnaDUfJ0UFzvlwI+mhXFjPQNJGXubXcWyQA==,iv:7v602oF4riKzyypYa9ny94AkrwC54yQ65m4eNCq/QmI=,tag:fUBKLMEjW+UVtsUTB5MgSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n7n73hztvwkq43gskmeddawn5w638dh30g0jycfxvn4h7ek9yvfq8tesqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWUQ1TjB4dG12Z2EyM2wx
            ZnRMVGMxMkRNM3ZXcC9IcmdGUFZBYmZkWUhzClBJZHNBWTJYdWZoTGNHMXRUb1VN
            U3kyTnNBY0gvWUU2dlpxSytQTFJLRGMKLS0tIFdqS3d5Ri9td2tsc1YvcHhaUkww
            cjF6NlQxQzlvbmJaU0dzSjE2KzlXMkEKWk2LzYnfVbqh5E4PqQRBV/ILvks+9OcV
            DHlWOHnk5Iz1xZFi/wrZIebcv8Rpu7PA2LiEwr3jtqNilrpwP3tP6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T08:24:12Z"
    mac: ENC[AES256_GCM,data:EF8KaZBjiogD4aS0zua2OTe6qfzzcyLk/rJH/kkB4g11R/JY7kKzWg2345L2n/7zq5EMtj/L5TlUF3UGM7idaTmmpO49u39herVGV43off/6PJeHmGKe+GLK0ZDaucTe3BhHPhGwtD1BbSds52JufxWTWEGayV8ZLAM04UYf08c=,iv:xAF0/Bf/Q3VaJQFPC5LkiJpwKtLixFpcnUySKaky5Dk=,tag:kDx7KfJ7XnPRxpkg8RqW6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
