apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:5uLBT3EAQrVsgsaiRkrFNvE7yUyg0XpAnXWdtKoofVbCzZhHz68zj9o5icOk6F7lxNMFqOI=,iv:1AOhm5i+eNAkvpElDpD93cKrNRva1AuO1iGOYTT0C2g=,tag:Nkbm1WN5S/00oYqdpKL+qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNXdmYk9lVGRucGNVVzBJ
            bGZJRUZZWTVpVk5EenB3b2FVcjJUdXJIMEhrCjVlU1RSeU1taDByd1JJUG5ORU1S
            aEZRR0VFem1oNk9hMVdIRUhpUndpUUkKLS0tIE15MTZ5cnd3clc5NXpHL1Q5YmU5
            MmVUdXlsSGdaVjRGcW9kbjd0Q0IySlkKsq8R5nLBrn65gzKp8HqUSlHRTObEhXNh
            0epbKekUQDsVrfzixbttn0EFXnEK/Ye+19iAdmrCch5Zlg2MS5H4oA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7n73hztvwkq43gskmeddawn5w638dh30g0jycfxvn4h7ek9yvfq8tesqz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T04:23:09Z"
    mac: ENC[AES256_GCM,data:YLuYlLTM2zxB9nU7jUwwfImk+MyaiUxLmKJq9NJqGd88jWBXialFKaPkoSYV7T/CMVE8obJLX+CCPbYYVpIwkWM36dSStd87OSvfONQmVsiSw5VenACHxKNdRuURXN63d+fqUpCt5EVQkgFBrYIeMjXaARO9pVjLsrGWVpuWfFA=,iv:o2jAjHngninHrkC0jsPEGM7jiJuAzjFtNQg7OS8fOgg=,tag:OtghVIh70DDZO0iG+4tDBA==,type:str]
    version: 3.9.0
