mqtt:
  enabled: true
  host: 192.168.8.31
  user: mqtt
  password: Mc2KMw2GHZgzpnnBcQqs
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 20

record:
  enabled: true
  retain:
    days: 30
    mode: motion
  events:
    retain:
      default: 30
      mode: active_objects

objects:
  track: [person]
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7
go2rtc:
  streams:
    study:
      - rtsp://admin:xxxxxxxx@10.10.20.142:554/Preview_01_main
    dining-room:
      - rtsp://admin:xxxxxxxx@10.10.20.171:554/Preview_01_main
    garage:
      - rtsp://admin:xxxxxxxx@10.10.20.83:554/Preview_01_main
    front-garden:
      - rtsp://admin:xxxxxxxx@10.10.20.155:554/h264Preview_01_main
    back-garden:
      - rtsp://admin:xxxxxxxx@10.10.20.81:554/h264Preview_01_main
cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 10
  front-garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front-garden
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 10
  back-garden:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back-garden
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 10
    objects:
      filters:
        person:
          mask: 0.214,0.426,0.234,0.612,0.596,0.628,0.588,0.475
  study:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/study
          input_args: preset-rtsp-restream
          roles:
            - detect
            - clips
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 10
    objects:
      filters:
        person:
          mask: 0.106,0.356,0.218,0.356,0.216,0.54,0.113,0.55
    zones:
      Front_Door:
        coordinates: 0.798,0.103,0.392,0.079,0.387,0.326,0.804,0.354
        loitering_time: 2
        objects: person
  dining-room:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/dining-room
          input_args: preset-rtsp-restream
          roles:
            - detect
    snapshots:
      enabled: true
      timestamp: true
      bounding_box: true
      retain:
        default: 2
    record:
      enabled: true
      retain:
        days: 10
version: 0.14
