---
# yaml-language-server: $schema=https://frigate.zinn.ca/api/config/schema.json
logger:
  default: info
  # logs:
  #   frigate.record: debug

auth:
  enabled: false

mqtt:
  host: "{FRIGATE_MQTT_HOST}"
  topic_prefix: frigate
  user: "{FRIGATE_MQTT_USERNAME}"
  password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /config/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  global_args: [-hide_banner, -loglevel, warning]
  hwaccel_args: preset-intel-qsv-h264
  output_args:
    record: preset-record-ubiquiti

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 20

record:
  enabled: true
  retain:
    days: 30
    mode: all
  events:
    retain:
      default: 30
      mode: active_objects

objects:
  track: [person, dog, cat]
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

cameras:
  backdoor:
    ffmpeg:
      inputs:
        - path: rtsp://admin:s3ndmail@10.10.20.142:554/Preview_01_main
          roles: [detect]
    detect:
      width: 1280
      height: 720
      fps: 24
