---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: send
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # dependsOn:
  #   - name: send-redis
  #     namespace: utilities
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: registry.gitlab.com/timvisee/send
              tag: v3.4.23
            env:
              TZ: "${TZ}"
              BASE_URL: "send.${SECRET_DOMAIN}"
              REDIS_HOST: dragonfly.database.svc.cluster.local
              REDIS_PORT: 6379
              FILE_DIR: /uploads
              MAX_FILE_SIZE: 5368709120
              MAX_EXPIRE_SECONDS: 2630000
              DEFAULT_DOWNLOADS: 50
              EXPIRE_TIMES_SECONDS: 3600,86400,604800,2592000,31536000
            # envFrom:
            #   - secretRef:
            #       name: send-secret
    defaultPodOptions:
      securityContext:
        # runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        controller: main
        ports:
          http:
            enabled: true
            port: 1443
    persistence:
      data:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 15Gi
        globalMounts:
          - path: /uploads
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 5G
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Utilities
          gethomepage.dev/name: Send
          gethomepage.dev/icon: mdi-email
        hosts:
          - host: &host "send.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
