---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: send-redis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: "8"
            # yamllint disable rule:indentation
            command:
              [
                "redis-server",
                "--requirepass",
                "$(REDIS_PASSWORD)",
                "--save",
                "",
                "--appendonly",
                "yes",
              ]
            # yamllint enable rule:indentation
            env:
              REDIS_REPLICATION_MODE: master
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: send-secret
                    key: REDIS_PASSWORD
    persistence:
      data:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /data
    service:
      main:
        controller: main
        ports:
          http:
            port: 6379
